apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.137.5-192.168.137.8
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mymetalb
  namespace: metallb-system
